 version: "3.3"

 services:
   api-students:
     build: ./api-students
     ports:
       - 8000:8000
   websimple:
     build: ./websimple
     ports:
       - 8080:80
   webPro:
     build: ./webPro
     ports:
      - 8081:80
